name: "CodeQL Advanced"

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "apps/docs/**"
      - "**.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "apps/docs/**"
      - "**.md"
  schedule:
    - cron: "28 20 * * 5"

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: [self-host-linux]
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: javascript-typescript
            build-mode: none
          - language: rust
            build-mode: none

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js v24
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          config: |
            paths-ignore:
              - 'apps/docs/**'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:${{matrix.language}}"
